module.exports = {
    rules: {
        'pinterest/cssclassname-extends-from-parent': 1,
        'pinterest/no-accessing-private-members': 0,
        'pinterest/no-bind-within-jquery': 2,
        'pinterest/no-callbacks-where-promises': 0,
        'pinterest/no-commented-out-tests': 2,
        'pinterest/no-data-options-dot-notation': 2,
        'pinterest/no-direct-p-pubsub-subscribe-call-in-modules': 2,
        'pinterest/no-duplicate-jquery-selectors': 2,
        'pinterest/no-goog-provide': 2,
        'pinterest/no-goog-require': 2,
        'pinterest/no-invalid-binds': 2,
        'pinterest/no-jquery-outside-of-render': 2,
        'pinterest/no-jquery-var-without-$': 2,
        'pinterest/no-listen-childListen-bind': 2,
        'pinterest/no-module-member-variables': 0,
        'pinterest/no-mutable-module-options': 0,
        'pinterest/no-private-functions-without-annotation': 0,
        'pinterest/no-reassigning-keywords': 2,
        'pinterest/no-reassigning-of-pubsub-topic-in-module': 2,
        'pinterest/no-reassigning-requires': 2,
        'pinterest/no-referencing-$el': 0,
        'pinterest/no-referencing-p-properties': 2,
        'pinterest/no-this-without-bind': 2,
        'pinterest/no-translation-outside-of-function': 2,
        'pinterest/no-unassigned-requires': 0,
        'pinterest/no-unhandled-promise-errors': 0,
    }
};
